export default function TermsContent() {
    return (
        <div className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
            <header className="mb-12 border-b border-gray-100 dark:border-gray-800 pb-8 text-center md:text-left">
                <h1 className="text-4xl md:text-5xl font-black text-[#131118] dark:text-white mb-4">
                    Terms & Conditions
                </h1>
                <div className="flex flex-wrap items-center justify-center md:justify-start gap-4 text-sm">
                    <span className="text-gray-500 dark:text-gray-400">
                        Last Updated: June 15, 2024
                    </span>
                    <span className="hidden sm:inline text-gray-300">|</span>
                    <a
                        className="text-primary font-medium hover:underline flex items-center gap-1"
                        href="mailto:legal@aiutilities.com"
                    >
                        <span className="material-symbols-outlined text-sm">mail</span>
                        legal@aiutilities.com
                    </a>
                </div>
            </header>
            <div className="space-y-12">
                <section id="acceptance">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        1. Acceptance of Terms
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        By accessing or using Ai Utilities (the &quot;Service&quot;), you agree to
                        be bound by these Terms &amp; Conditions. If you do not agree to all
                        of the terms and conditions, you may not use our Service.
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        We reserve the right to modify these terms at any time. We will
                        notify users of any significant changes by posting a notice on our
                        platform or via email.
                    </p>
                </section>

                <section id="service">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        2. Use of Service
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        The Service provides AI-powered content generation tools including
                        essay generators, summarizers, and humanizers. Your use of these
                        tools is subject to the following conditions:
                    </p>
                    <ol className="list-decimal pl-6 space-y-4 text-gray-600 dark:text-gray-400 mb-8">
                        <li className="pl-2">You must be at least 13 years of age to use this Service.</li>
                        <li className="pl-2">
                            You are responsible for maintaining the confidentiality of your
                            account credentials.
                        </li>
                        <li className="pl-2">
                            The outputs generated by the AI are for your personal or
                            professional use, subject to the copyright terms outlined below.
                        </li>
                        <li className="pl-2">
                            You acknowledge that AI outputs may occasionally be inaccurate or
                            biased.
                        </li>
                    </ol>
                </section>

                <section id="privacy">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        3. Privacy &amp; Data
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        Your privacy is important to us. Our use of your personal
                        information and data provided to the Service is governed by our
                        Privacy Policy. By using the Service, you consent to the collection
                        and use of this information.
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        We do not sell your personal data. Content you input into our tools
                        is processed to generate results and may be used in an anonymized
                        format to improve our models, unless you opt-out in your account
                        settings.
                    </p>
                </section>

                <section id="conduct">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        4. User Conduct
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        You agree not to use the Service for any unlawful or prohibited
                        purposes. Prohibited activities include, but are not limited to:
                    </p>
                    <ol className="list-decimal pl-6 space-y-4 text-gray-600 dark:text-gray-400 mb-8">
                        <li className="pl-2">
                            Generating content that is defamatory, obscene, or promotes hate
                            speech.
                        </li>
                        <li className="pl-2">
                            Attempting to bypass any security measures or rate limits of the
                            Service.
                        </li>
                        <li className="pl-2">
                            Using the Service to create academic work for submission where
                            such use is prohibited by the educational institution.
                        </li>
                        <li className="pl-2">
                            Automated scraping or extraction of data from the Service without
                            prior written consent.
                        </li>
                    </ol>
                </section>

                <section id="payments">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        5. Payments &amp; Billing
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        Certain features of Ai Utilities require a paid subscription. By
                        subscribing, you agree to:
                    </p>
                    <ol className="list-decimal pl-6 space-y-4 text-gray-600 dark:text-gray-400 mb-8">
                        <li className="pl-2">Provide accurate billing information.</li>
                        <li className="pl-2">
                            Pay all fees associated with your chosen plan on the designated
                            billing date.
                        </li>
                        <li className="pl-2">
                            Understand that all payments are non-refundable except as required
                            by law.
                        </li>
                    </ol>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        Subscriptions will automatically renew unless cancelled at least 24
                        hours before the end of the current billing cycle.
                    </p>
                </section>

                <section id="intellectual">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        6. Intellectual Property
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        The Service, including its original content, features, and
                        functionality, is owned by Ai Utilities and protected by
                        international copyright and trademark laws.
                    </p>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        Regarding AI-generated outputs: We grant you a perpetual, worldwide,
                        non-exclusive license to use, modify, and distribute the content
                        generated for you through our Service for any legal purpose.
                    </p>
                </section>

                <section id="termination">
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">
                        7. Termination
                    </h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        We reserve the right to terminate or suspend your account and access
                        to the Service immediately, without prior notice or liability, for
                        any reason, including without limitation if you breach the Terms.
                    </p>
                </section>

                <section
                    className="mt-16 p-8 bg-gray-50 dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-700"
                    id="contact-legal"
                >
                    <h2 className="text-2xl font-bold text-[#131118] dark:text-white mb-4">Legal Inquiries</h2>
                    <p className="text-gray-600 dark:text-gray-400 mb-4 leading-relaxed">
                        If you have any questions about these Terms &amp; Conditions, please
                        contact our legal department:
                    </p>
                    <div className="flex flex-col gap-3 mt-6">
                        <div className="flex items-center gap-3">
                            <span className="material-symbols-outlined text-primary">
                                email
                            </span>
                            <span className="text-gray-700 dark:text-gray-300">
                                legal@aiutilities.com
                            </span>
                        </div>
                        <div className="flex items-center gap-3">
                            <span className="material-symbols-outlined text-primary">
                                location_on
                            </span>
                            <span className="text-gray-700 dark:text-gray-300">
                                123 AI Boulevard, Tech City, TC 10101
                            </span>
                        </div>
                    </div>
                    <button className="mt-8 brand-gradient text-white font-bold py-3 px-8 rounded-lg transition-all shadow-lg hover:shadow-primary/20">
                        Contact Support Form
                    </button>
                </section>
            </div>
        </div>
    );
}
